title: Custom NPC Docs
description: Docs on how to make and use custom npcs in hollow knight!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  CustomNPCDocs Repo: https://github.com/Zickles/CustomNPCDocs/
